### ISSUE TITLE
有非常多的HTTP Auto Proxy进程，结束进程非常麻烦

### ISSUE THREAD

**Issue by willaytoun** [atestsoft/ssr#3]
有时要剪切或者删除SSR文件夹，后台进程太多要结束的话非常麻烦必须要重启机器。不知道这些进程是否必须所以请教下作者，如果是必须的话也没什么大问题。感谢大佬的更新~~
![SSR进程](https://user-images.githubusercontent.com/43229736/55472954-eff12f00-563f-11e9-9f33-4e9f35392349.png)

**Comment by atestsoft** [comment]
这个问题经过探索,应该时微软1809版本的策略问题,目前在新版win10中应该已经修复.
首先说明一下,这个进程时windows系统创建的进程,并非ssr进程.
然后ssr在修改pac后为了更新系统设置,会给pac链接附加时间戳参数导致系统创建不同的pac进程并且不停止之前的旧进程.

详情见:
https://github.com/shadowsocks/shadowsocks-windows/issues/1979
https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/
https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/149

**Comment by willaytoun** [comment]
感谢大佬如此快的回复。我平常开关机的时候习惯点一下检查更新，系统版本感觉应该是最新的。如果是win10的问题的话我用的盗版系统不知道反馈有没有用，如果没用的话其实也还好不是特别影响使用的：)
[image: win10更新记录.png]


atestsoft <notifications@github.com> 于2019年4月3日周三 下午7:46写道：
